services:
  core: 
    build: ./core
    container_name: core
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local
